services:
  kestra_postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      # Postgres 18+ uses a version-specific default PGDATA
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      # For Postgres 18+, mount at /var/lib/postgresql (not /var/lib/postgresql/data)
      - kestra_postgres_data:/var/lib/postgresql

  kestra:
    image: kestra/kestra:v1.1
    command: server standalone
    user: "root"   # keep if you use Docker socket tasks
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - kestra_data:/app/storage
      - kestra_tmp:/tmp/kestra-wd
      - /var/run/docker.sock:/var/run/docker.sock
    # to read the encoded keys in Kestra
    env_file:
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              username: "admin@local.dev"
              password: Admin123
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    depends_on:
      - kestra_postgres

volumes:
  kestra_postgres_data:
  kestra_data:
  kestra_tmp:
